### ISSUE TITLE
Edit page button

### ISSUE THREAD

**Issue by sposth** [internet-sicherheit/eBGF#1]
Edit page button is not linked correctly and produces a 404 message. 

![grafik](https://user-images.githubusercontent.com/14913025/113344230-17635b00-9331-11eb-87d2-92ec1fb0de49.png)

The button here: 
https://internet-sicherheit.github.io/eBGF/RFC/1-inst/RFC-1001/

Links to: 
https://github.com/internet-sicherheit/eBGF/edit/master/docs/RFC/1-inst/RFC-1001.md

This produces a 404.

Could this be solved?

**Comment by kiview** [comment]
It needs to link to `main` instead of `master`, since the seemingly new GitHub default branch name convention is to use `main`.

**Comment by sposth** [comment]
In what file can this be fixed?

**Comment by kiview** [comment]
In the `mkdocs.yml`, by [configuring](https://www.mkdocs.org/user-guide/configuration/#edit_uri) the `edit_uri` correctly.

**Comment by danthe21** [comment]
Problem should be resolved. Mkdocs uses 'edit/master/docs/' by default as edit_uri. Added the correct edit_uri entry to the .yml file.
